### ISSUE TITLE
Means of identifying background or foreground color without a declaration

### ISSUE THREAD

**Issue by davidtheclark** [jonathantneal/postcss-wcag-contrast#1]
A pretty significant limitation of this plugin is that it can only compare background/foreground colors within single rules. That should certainly be noted in the Readme, I think.

But I wonder if there are any ways to get around that. One way I thought might work, for those who are serious about using this plugin to enforce WCAG standards, would be to read a special comment in rules that declares the background/foreground color within having to make a declaration.

For example, let's say the background of my `body` is `#eee`. I'm not going to declare that background all over the place, but most of the text on my page will be foregrounded against it. So wherever I declare my text color, I could add a special comment noting the background:

``` css
.headline {
  /* postcss-contrastguard background: #eee */
  color: #333;
}
```

What do you think?

**Comment by jonathantneal** [comment]
I think it’s a very helpful idea. I’ll look into ways to do this, similar to or exactly as what you’ve described.

**Comment by jonathantneal** [comment]
Great idea, and this has been added to the [v1 release](https://github.com/jonathantneal/postcss-wcag-contrast/tree/v1.0.0).
